apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pr-agent-app
  template:
    metadata:
      labels:
        app: pr-agent-app
    spec:
      containers:
        - name: pr-agent-app
          image: <ACR_LINK>/kaito-pr-agent:latest
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          ports:
            - containerPort: 3000
          # Mount secrets volume
          volumeMounts:
            - mountPath: "/app/pr_agent/settings_prod/.secrets.toml"
              subPath: .secrets.toml
              name: secrets-volume
      volumes:
        - name: secrets-volume
          secret:
            secretName: kaito-pr-agent-secrets
