apiVersion: v1
kind: ConfigMap
metadata:
  name: pr-agent-config
data:
  allowed_repos.toml: |
    [default]
    allowed_repos = [
      "https://github.com/kaito-project/kaito",
      "https://github.com/ishaansehgal99/kaito-pr-review-demo"
    ]
